### ISSUE TITLE
Formatting issue in SRS

### ISSUE THREAD

**Issue by Sodaaaa** [smiths/swhs#20]
In Section 5.1 Functional Requirements, R10 and R11 are not indented as far as others.

**Comment by bmaclach** [comment]
For me, the requirements list looks like this:

![reqs](https://cloud.githubusercontent.com/assets/18634568/16990449/0ccb4604-4e66-11e6-96b3-b5e68815533d.png)

Is that how it appears for you as well? If so, I think the reason R10 and R11 are slightly less indented than the others is just so that the colons are aligned throughout the list, which is just the way that LaTeX handles itemized lists.

**Comment by Sodaaaa** [comment]
Yes, I think you are right. I'll just close this issue.
