### ISSUE TITLE
Two makefiles?

### ISSUE THREAD

**Issue by smiths** [smiths/swhs#27]
CCode has two makefiles: one in CCode itself and one in the Makefile folder.  I just used the one in the CCode folder.  Is the Makefile folder necessary?  If yes, it should be explained in the README file.  If no, we should remove it from version control.

**Comment by bmaclach** [comment]
The Makefiles folder is not necessary. I originally made it because you had committed a makefile that worked for your system and I wanted to store that one for you. Now that you've committed a version of the makefile that can be easily changed to work for you, we definitely don't need the other one. I'll go ahead and remove that folder from the repository.

**Comment by smiths** [comment]
Sounds good.  Thank you Brooks.
