### ISSUE TITLE
PCM_SRS: Missing Description

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#33]
For the DD2 table, the equation has an A<sub>p</sub> symbol but does not provide a description for it.

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39711261-396ebd30-51ed-11e8-803a-b1525d542add.png)

The A<sub>p</sub> is refered to in the Equation row

**Comment by smiths** [comment]
@elwazana, you are correct that Ap should be defined under the description.  Can you please check the Drasil (generated) version of this documentation.  If Ap is not defined in that documentation, then please create an issue (referencing this issue) to fix the generated documentation.

**Comment by elwazana** [comment]
@smiths So in the generated and stable the "over area _A<sub>p</sub>_" isn't even there:

(Stable and Generated aren't differet)
![image](https://user-images.githubusercontent.com/35268928/40919598-f56265f0-67d7-11e8-9a93-656afba5b096.png)

**Comment by smiths** [comment]
@JacquesCarette and @szymczdm, I think this discussion will interest you.  

@elwazana thank you for investigating.  The difference between the manual version and the generated (and stable) versions represents a loss of knowledge.  There have been other instances in the past where the person translating some of the knowledge didn't know how to fit it in, so they just ignored it.  Although understandable, this is not a good solution.

The actual fix should be small, but it highlights how careful we need to be to not lose information in our zeal for automation.

The fact that qp acts over Ap is critical information.  If we don't know what area qp acts over, then we cannot derive the energy balance equation.  The information that qp acts over Ap does not have to be with the Equation (if doesn't fit with the Drasil DSL), but it does have to be somewhere.

I do not know why Ap was left out.  My thinking is that if putting it with the equation is difficult, the information could go with the description.  The description in this case just lists the meaning of the symbols in the equation.  This list is great (and necessary) information, but Drasil hasn't changed so that we cannot add a blurb in the description field, right?  We used to do this.

In my investigation of this issue, I've pinpointed when the information was deleted.  In our effort to have stable and manual match, Yuzhi deleted it.  I noticed this in my review of Yuzhi's changes, but I didn't follow up at the time.  (I did mention in the commit message, but I guess it got lost in all the other things going on at the time.)  It is a detail that fell through the cracks.  You can see the commit where the change was made and the note about the lost information at:

https://github.com/smiths/swhs/commit/0fa29b3812e325c38c69f9e99aed687a5938380d#diff-6b015faba2d3c0db62a13cbc81854c96  

(Search for "assumptions? [SS]")

An advantage of Drasil is that we can capture the information once and then reuse it.  The fact that I have to keep thinking about the assumptions for the use of the equation for qp is not a good sign for our process.  I think I'm a good physicist, but I'm not good enough that it isn't some effort every time, and if the workload is high, there is a chance of a mistake getting introduced.  I want the expert to make the effort once, and not to have to think about it again.  😄 

The LaTeX that was removed from "Heat Flux Into the PCM From Water" is as follows:

```
The heat flux into the PCM, $q_P$ (\si{\watt\per\square\metre}), is found by assuming 
that Newton's Law of Cooling applies (\aref{A_Newt_pcm}).  This law (\dref{NL}) is used 
on the surface of the PCM, which has area $A_P$ (\si{\square\metre}) and heat transfer 
coefficient $h_P$ (\si{\watt\per\square\metre\per\celsius}).  This equation assumes 
that the temperature of the PCM and water each have constant values over the surface 
area over which they interact (\aref{A_mixed} and \aref{A_tpcm}).
```

The missing information is as follows:

- that Newton's law of cooling applies.  This is an assumption that the equation depends.  This is the critical traceability information that we promote as an advantage of Drasil.
- the thermal flux acts over the area $A_P$
- the assumptions that the temperatures are constant over time and over space

In investigating this, I found my notes that the same kind of mistake was made elsewhere.  The most recent version of the manual version is missing information on the derivations.  You can see the examples at the link given above, when searching for [SS].  There are 5 separate instances.

I think we should discuss each of the 5 differences between the previous version of SWHS and the current version.  The fix might just to be add Sentences, but there might be something else going on here.  Maybe there is a chance for a deeper understanding of what kind of information we are capturing?  Drasil is not just Equations.  The GlassBR example might make it look like that, but information is rarely as simple as an explicit equation with the quantity desired isolated on the left hand side of the equation.

@elwazana, please create a separate issue for each of the 5 discrepancies.  We may use our meeting tomorrow (Tuesday, June 5) to go through each of these issues.  I feel like this might be a moment for us to learn about Drasil.  At the very least, we want to look at our process so that we don't repeat the mistake of losing information again.

One problem that keeps coming up is that people forget that SWHS is a separate repo.  It should not be in Case Studies.  I am going to add everyone in the Drasil team as contributors to SWHS so that its visibility is increased.

**Comment by smiths** [comment]
Since this issue has been decomposed into other issues, we can close the original issue.
