### ISSUE TITLE
PCM_SRS: Missing Description

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#35]
Many tables in section 4.2.5, many tables provide a list of inputs, however, many of these inputs do not have descriptions. Such as C<sub>w</sub> and _m_<sub>w</sub>.

**Comment by smiths** [comment]
Too vague.  We need specifics.  It is tedious, but for changes we actually make, the next step will be to update the stable (Drasil) version.  We need to make sure that we don't lose track of something.

**Comment by elwazana** [comment]
![image](https://user-images.githubusercontent.com/35268928/39631594-9b4b3ebc-4f80-11e8-98e9-4065c7799b6f.png)

C<sub>w</sub> and _m_<sub>w</sub> are referred to in the input section, however, they are not given a description in the appropriate section. Doing so may improve readability and improve clarity.

**Comment by smiths** [comment]
@elwazana, I agree with you that C_w and m_w should be defined as well.  What happens in a list like this in the generated (Drasil) code.  Are C_w and m_w described there?  (I haven't checked.)  That would imply a recursive definition where if symbols are defined in terms of other symbols, then those other symbols are also described.  I don't remember a discussion about doing the symbol descriptions recursively, but maybe we do?

**Comment by elwazana** [comment]
@smiths The Drasil generated is:
![image](https://user-images.githubusercontent.com/35268928/42236917-4ac483da-7eca-11e8-94e5-144d38cd0a1e.png)

This is from the most up-to-date current master.

**Comment by smiths** [comment]
@elwazana, this is good to know.  I wasn't aware that the SWHS example is behind the GlassBR example.  For instance, when @niazim3 generates the GlassBR example the description is automatically generated.  It consists of definitions of the symbols used to build the equation.  @niazim3, when you generate the description, is it done recursively?  That is, if a symbol depends on other symbols, are those other symbols expanded too?  For instance, would the symbols in tau_W (above) be expanded?  My guess is no, especially since there will be cases where the symbol appears both in the original equation and in the definition for one or more of the symbols for the original equation.

**Comment by niazim3** [comment]
The SWHS example has been updated to automatically generate the descriptions in @halonazhao's [yuzhi](https://github.com/JacquesCarette/Drasil/tree/yuzhi) branch; this is currently generated for the example:
![image](https://user-images.githubusercontent.com/28247301/42244059-7140d2b8-7ee1-11e8-9e26-83a14cc2c042.png)

I don't believe Drasil currently supports recursive descriptions or even displaying what τ<sub>W</sub> is equal to (i.e. the equation that actually contains ) in the table describing an instance model.

**Comment by smiths** [comment]
@szymczdm, what are your thoughts on this issue?  The equation for IM1 depends on tau_W and tau_W itself is defined by an equation.  This information is summarized in the manual version, which could itself be further improved by defining all of the symbols in the definition of tau_W.  The generated version loses the equation for tau_W.  What options do we have for keeping it.  Can equations have a "where" clause that defines undefined terms?  Can the description list be recursive?  What options do you see?

**Comment by niazim3** [comment]
Wanted to note that the derivation for this instance model does contain the equation for tau_W.
![image](https://user-images.githubusercontent.com/28247301/42278085-9695feae-7f67-11e8-8157-128199c269c9.png)

**Comment by smiths** [comment]
Thank you for the note @niazim3.  This is definitely a problem that we should fix.

**Comment by szymczdm** [comment]
I think recursive definitions can be tricky. I think it would be an interesting option to include, but we'll need to be very specific with how far we go. Defining one level deeper shouldn't cause any problems, but going further than that could (due to use of short-hand where things are defined using their own symbols, added bloat from too many descriptions, etc).

**Comment by smiths** [comment]
@elwazana, this issue was discussed by @JacquesCarette, @szymczdm and myself during a recent meeting.  In the long (medium?) term we would like to have a local scope to our information where we can define symbols that are locally meaningful.  Currently all symbols are global.  This means that to be consistent symbols like \tau_w need to get a higher level treatment than they probably deserve, especially since \tau_w isn't particularly physically meaningful.  (I suppose it is related to the heating rate from solving the ODE.)

In the short term, for consistency, let us add a data definition for \tau_w.  This data definition can then be referenced in the original instance model that sparked this discussion.

@elwazana, please modify the SWHS SRS in the case study repo to include the \tau_w data definition, along with appropriate updates to IM1.  Once we have discussed these changes, the next step will be to correspondingly modify the Drasil code.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, here is the data definition for \tau_w:
![image](https://user-images.githubusercontent.com/35268928/42469168-f2fb324c-8384-11e8-867f-ddb63be7e420.png)

Along with the updated IM1:
![image](https://user-images.githubusercontent.com/35268928/42469204-0cacbdaa-8385-11e8-84e9-3a05b7b53ea7.png)
Is there anything else I should add to the IM1?

**Comment by smiths** [comment]
Thanks @elwazana.  We need a better label for DD3.  We should avoid meaningless numbers in names if at all possible.  How about "Energy Balance Water Decay Time"?  The Units field for DD3 is incorrect.  It should be t.  Also, we no longer use the Units field.  You can just delete that row completely.  The SI units are technically correct, but they simplify to s, so I suggest you just put s in t his field.

For IM1 you should no longer list C_W and m_W.  The motivation for this change was to remove this problem from the manual and the generated versions.  Your input instead should be \tau_W.  The description field that mentions \tau_W should reference DD3.

In the derivation part following IM1, please explicitly reference DD3.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, is this ok?

Data Definition:
![image](https://user-images.githubusercontent.com/35268928/42473802-9fb2575a-8393-11e8-8e60-f868aec51bd6.png)

Instance Model:
![image](https://user-images.githubusercontent.com/35268928/42473836-b5b3b59e-8393-11e8-86c7-01e0a4954372.png)

Derivation:
![image](https://user-images.githubusercontent.com/35268928/42473874-d2c38a74-8393-11e8-8bd5-4acd32d72611.png)

**Comment by smiths** [comment]
Close.  😄  For DD3 for the Description, please list the units of each symbol.  (Isn't it nice that Drasil does this automatically!)  Also for DD3, please list the source as [4] (Marilyn Lightstone's notes).

For IM1 you don't want DD3 just sitting beside \tau_W without context or explanation.  Simply putting (from DD3) in brackets should be fine.

For the derivation below DD3 again just shows up.  Again, I suggest putting (from DD3) after the definition of \tau_W.

Shouldn't \eta should get a similar treatment?  If I am not mistaken, \eta will also be undefined (unexpanded) in the Drasil version.  We can solve this foreseeable problem in the same way that we sorted things out for \taw_W.

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, here are the changes:

The DDs (bottom is \eta):
![image](https://user-images.githubusercontent.com/35268928/42524824-97851dae-843f-11e8-86c9-4e5c752c9d55.png)
I know you don't like the Balance Constant 2 as the Label but I was unsure as to what to change it to.

The IM:
![image](https://user-images.githubusercontent.com/35268928/42524916-dd7547c6-843f-11e8-97fe-32dee25655d7.png)
![image](https://user-images.githubusercontent.com/35268928/42525039-301de46a-8440-11e8-9419-682a77db9716.png)

**Comment by smiths** [comment]
Very close now.  😄 The source for DD4 should be Dr. Lightstone [4] and for DD4 dimensionless is spelt incorrectly.  It isn't that big a difference, but in the derivation, I would prefer the brackets come after the equation.  That is, "Setting \tau_W = m_W.. (from DD3)" and similarly for DD4.  As far as the name for eta goes, let us call it "Energy Balance Water Decay Rate."

**Comment by elwazana** [comment]
@smiths Hello Dr. Smith, Here are the requested changes:

DD4:
![image](https://user-images.githubusercontent.com/35268928/42534654-3f5d8e2e-845b-11e8-94f1-6a686427e483.png)


Derivation:
![image](https://user-images.githubusercontent.com/35268928/42534616-1ad39030-845b-11e8-9336-7a770ea669dc.png)

**Comment by smiths** [comment]
Looks good!  Please propagate these changes to Drasil.  You should make a new issue there with a pointer (html link) back to this issue.  I believe that you can close this issue now.
