### ISSUE TITLE
PCM_MIS: Misalignment of Section

### ISSUE THREAD

**Issue by elwazana** [smiths/swhs#36]
Section 1 is placed above the table of contents.

**Comment by elwazana** [comment]
https://github.com/smiths/swhs/blob/master/MIS/PCM_MIS.pdf

**Comment by smiths** [comment]
Thank you @elwazana.  You are correct that we usually want the table of contents before the table of symbols.  Please make the change.  Since the MIS is not yet part of Drasil, there will be no further changes necessary at this time.  Once you make the change, you can close this issue.  Please include the hash code for the commit that closes the issue.

**Comment by elwazana** [comment]
8e558077aa08d83502d9e0bf82686f92c15e7f3f
